server.port=${PORT:8080}
spring.application.name=miticultor-backend

# Railway PostgreSQL Configuration
spring.datasource.url=jdbc:postgresql://yamabiko.proxy.rlwy.net:33838/railway
spring.datasource.username=postgres
spring.datasource.password=zVDLOJAjIrIXyFBVFIVCpILVVWTjXhxt

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
